User.create(username: "wu", password: "Poop1", email: "jpwu03@yahoo.com")
Form.create(title: "Team Topher", url: "poop.com", user_id: 1)
Question.create(question: "Who would win in a wizard duel", form_id: 1)
Option.create(answer: "Topher", question_id: 1)
Option.create(answer: "Dumbledore", question_id: 1)
Question.create(question: "Who would lose in a wizard duel", form_id: 1)
Option.create(answer: "Topher", question_id: 2)
Option.create(answer: "Gandalf", question_id: 2)
